language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: tests
      name: "Unit tests"
      script: 
        - cd test && npm install 
        - cd .. && npm run test && npm run coverage